// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewFollowProjectParams creates a new FollowProjectParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewFollowProjectParams() *FollowProjectParams {
	return &FollowProjectParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewFollowProjectParamsWithTimeout creates a new FollowProjectParams object
// with the ability to set a timeout on a request.
func NewFollowProjectParamsWithTimeout(timeout time.Duration) *FollowProjectParams {
	return &FollowProjectParams{
		timeout: timeout,
	}
}

// NewFollowProjectParamsWithContext creates a new FollowProjectParams object
// with the ability to set a context for a request.
func NewFollowProjectParamsWithContext(ctx context.Context) *FollowProjectParams {
	return &FollowProjectParams{
		Context: ctx,
	}
}

// NewFollowProjectParamsWithHTTPClient creates a new FollowProjectParams object
// with the ability to set a custom HTTPClient for a request.
func NewFollowProjectParamsWithHTTPClient(client *http.Client) *FollowProjectParams {
	return &FollowProjectParams{
		HTTPClient: client,
	}
}

/*
FollowProjectParams contains all the parameters to send to the API endpoint

	for the follow project operation.

	Typically these are written to a http.Request.
*/
type FollowProjectParams struct {

	/* ProjectSlug.

	     Project slug in the form vcs-slug/org-name/repo-name.
	The / characters may be URL-escaped.
	Example: gh/CircleCI-Public/api-preview-docs

	*/
	ProjectSlug string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the follow project params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *FollowProjectParams) WithDefaults() *FollowProjectParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the follow project params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *FollowProjectParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the follow project params
func (o *FollowProjectParams) WithTimeout(timeout time.Duration) *FollowProjectParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the follow project params
func (o *FollowProjectParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the follow project params
func (o *FollowProjectParams) WithContext(ctx context.Context) *FollowProjectParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the follow project params
func (o *FollowProjectParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the follow project params
func (o *FollowProjectParams) WithHTTPClient(client *http.Client) *FollowProjectParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the follow project params
func (o *FollowProjectParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithProjectSlug adds the projectSlug to the follow project params
func (o *FollowProjectParams) WithProjectSlug(projectSlug string) *FollowProjectParams {
	o.SetProjectSlug(projectSlug)
	return o
}

// SetProjectSlug adds the projectSlug to the follow project params
func (o *FollowProjectParams) SetProjectSlug(projectSlug string) {
	o.ProjectSlug = projectSlug
}

// WriteToRequest writes these params to a swagger request
func (o *FollowProjectParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param project-slug
	if err := r.SetPathParam("project-slug", o.ProjectSlug); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
