// Code generated by go-swagger; DO NOT EDIT.

package project

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/kelvintaywl/circleci-v1-go-sdk/models"
)

// ListProjectsReader is a Reader for the ListProjects structure.
type ListProjectsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListProjectsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewListProjectsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewListProjectsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewListProjectsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewListProjectsOK creates a ListProjectsOK with default headers values
func NewListProjectsOK() *ListProjectsOK {
	return &ListProjectsOK{}
}

/*
ListProjectsOK describes a response with status code 200, with default header values.

Project-follow information
*/
type ListProjectsOK struct {
	Payload *models.ProjectFollowInfo
}

// IsSuccess returns true when this list projects o k response has a 2xx status code
func (o *ListProjectsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this list projects o k response has a 3xx status code
func (o *ListProjectsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list projects o k response has a 4xx status code
func (o *ListProjectsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this list projects o k response has a 5xx status code
func (o *ListProjectsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this list projects o k response a status code equal to that given
func (o *ListProjectsOK) IsCode(code int) bool {
	return code == 200
}

func (o *ListProjectsOK) Error() string {
	return fmt.Sprintf("[POST /project/{project-slug}/follow][%d] listProjectsOK  %+v", 200, o.Payload)
}

func (o *ListProjectsOK) String() string {
	return fmt.Sprintf("[POST /project/{project-slug}/follow][%d] listProjectsOK  %+v", 200, o.Payload)
}

func (o *ListProjectsOK) GetPayload() *models.ProjectFollowInfo {
	return o.Payload
}

func (o *ListProjectsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ProjectFollowInfo)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListProjectsBadRequest creates a ListProjectsBadRequest with default headers values
func NewListProjectsBadRequest() *ListProjectsBadRequest {
	return &ListProjectsBadRequest{}
}

/*
ListProjectsBadRequest describes a response with status code 400, with default header values.

Invalid input
*/
type ListProjectsBadRequest struct {
	Payload *models.Errored
}

// IsSuccess returns true when this list projects bad request response has a 2xx status code
func (o *ListProjectsBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list projects bad request response has a 3xx status code
func (o *ListProjectsBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list projects bad request response has a 4xx status code
func (o *ListProjectsBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this list projects bad request response has a 5xx status code
func (o *ListProjectsBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this list projects bad request response a status code equal to that given
func (o *ListProjectsBadRequest) IsCode(code int) bool {
	return code == 400
}

func (o *ListProjectsBadRequest) Error() string {
	return fmt.Sprintf("[POST /project/{project-slug}/follow][%d] listProjectsBadRequest  %+v", 400, o.Payload)
}

func (o *ListProjectsBadRequest) String() string {
	return fmt.Sprintf("[POST /project/{project-slug}/follow][%d] listProjectsBadRequest  %+v", 400, o.Payload)
}

func (o *ListProjectsBadRequest) GetPayload() *models.Errored {
	return o.Payload
}

func (o *ListProjectsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Errored)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewListProjectsNotFound creates a ListProjectsNotFound with default headers values
func NewListProjectsNotFound() *ListProjectsNotFound {
	return &ListProjectsNotFound{}
}

/*
ListProjectsNotFound describes a response with status code 404, with default header values.

Not Found
*/
type ListProjectsNotFound struct {
	Payload *models.Errored
}

// IsSuccess returns true when this list projects not found response has a 2xx status code
func (o *ListProjectsNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this list projects not found response has a 3xx status code
func (o *ListProjectsNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this list projects not found response has a 4xx status code
func (o *ListProjectsNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this list projects not found response has a 5xx status code
func (o *ListProjectsNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this list projects not found response a status code equal to that given
func (o *ListProjectsNotFound) IsCode(code int) bool {
	return code == 404
}

func (o *ListProjectsNotFound) Error() string {
	return fmt.Sprintf("[POST /project/{project-slug}/follow][%d] listProjectsNotFound  %+v", 404, o.Payload)
}

func (o *ListProjectsNotFound) String() string {
	return fmt.Sprintf("[POST /project/{project-slug}/follow][%d] listProjectsNotFound  %+v", 404, o.Payload)
}

func (o *ListProjectsNotFound) GetPayload() *models.Errored {
	return o.Payload
}

func (o *ListProjectsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Errored)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
