// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// ProjectFollowInfo project follow info
//
// swagger:model ProjectFollowInfo
type ProjectFollowInfo struct {

	// first build
	FirstBuild *string `json:"first_build,omitempty"`

	// True if you follow this project in CircleCI
	// Example: true
	Followed bool `json:"followed,omitempty"`

	// True if a workflow is triggered
	// Example: true
	Workflow bool `json:"workflow,omitempty"`
}

// Validate validates this project follow info
func (m *ProjectFollowInfo) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this project follow info based on context it is used
func (m *ProjectFollowInfo) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ProjectFollowInfo) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ProjectFollowInfo) UnmarshalBinary(b []byte) error {
	var res ProjectFollowInfo
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
